# Generated by Django 4.2.6 on 2023-10-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=50)),
                ('depa_id', models.PositiveIntegerField(blank=True)),
                ('depa_name', models.CharField(blank=True, max_length=50)),
                ('salary', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
